### ISSUE TITLE
Oprava domácího úkolu Životopis

### ISSUE THREAD

**Issue by LenkaVer** [MariaSimkova/CV#1]
Ahoj Mario,
stránka je moc pěkná, skvělá práce.
Pár poznámek:

- [x] V sekci skills a education není u položek seznamu li nutné používat na konci řádku zalomení br, li začíná vždy na novém řádku.
Názvy tříd by měly být napsané malými písmeny, používá se kebab-case (tedy oddělování slov pomlčkou) spíše než camelCase (ten se používá spíše v javascriptu), případně nějaké konvence jako je BEM (budeme se učit dále v kurzu).
Pozor na nadužívání zalamování pomocí br, občas je lepší začít nový odstavec p a případně ho nastylovat.
Pozor na stylování pomocí id kvůli specificitě, lepší je přidat prvku další třídu a stylovat přes třídy a id používat jen v nezbytných případech.

**Comment by MariaSimkova** [comment]
Ahoj Lenko,

Mockrát děkuji za tvoje komentáře. Všechno jsem opravila:)
